# Site settings
baseurl = "http://pelagraca.bsrv.net/"
languageCode = "en-us"
title = "Pela Graça de Deus"
theme = "hugrid"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-111579631-1"

contentdir = "content"
datadir = "data"
layoutdir = "layouts"
publishdir = "public"

[params]
    # Meta
    title = "Pela Graça"
    subtitle = "Agregador de conteúdo Cristão."
    author = "Eduardo Falabella"
    description = "Agregador de conteúdo cristão"
    keywords = "acervo, links, acervo cristão, Senhor, agregador, Jesus, Cristo, Deus"

    # Body background color
    bodybgcolor = "#f9f9f9"

    # Preview container button text
    buttontext = "Visite o Site"

    # Footer text
    footertext = ""

    # add extra-css
    # custom_css = ['css/extra1.css', 'css/extra2.css']
